version: '3.8'
services:
  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:alpine
    env_file:
      - .env
    command: http 3000 --authtoken ${NGROK_AUTH_TOKEN} --subdomain ${NGROK_SUBDOMAIN}
    network_mode: host